# Generated by Django 5.2 on 2025-04-25 09:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('selling_price', models.FloatField()),
                ('discounted_price', models.FloatField()),
                ('description', models.TextField()),
                ('brand', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('M', 'Mobile'), ('L', 'Laptop'), ('TW', 'Top Wear'), ('BW', 'Bottom Wear')], max_length=2)),
                ('product_image', models.ImageField(upload_to='productimg')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('locality', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=50)),
                ('zipcode', models.IntegerField()),
                ('state', models.CharField(choices=[('Abbottabad', 'Abbottabad'), ('Bahawalpur', 'Bahawalpur'), ('Bannu', 'Bannu'), ('Bhakkar', 'Bhakkar'), ('Bhaun', 'Bhaun'), ('Chakwal', 'Chakwal'), ('Chaman', 'Chaman'), ('Chiniot', 'Chiniot'), ('Dadu', 'Dadu'), ('Dera Ghazi Khan', 'Dera Ghazi Khan'), ('Dera Ismail Khan', 'Dera Ismail Khan'), ('Faisalabad', 'Faisalabad'), ('Gilgit', 'Gilgit'), ('Gujrat', 'Gujrat'), ('Gujranwala', 'Gujranwala'), ('Gwadar', 'Gwadar'), ('Hyderabad', 'Hyderabad'), ('Islamabad', 'Islamabad'), ('Jaranwala', 'Jaranwala'), ('Jhelum', 'Jhelum'), ('Karachi', 'Karachi'), ('Kasur', 'Kasur'), ('Killa Saifullah', 'Killa Saifullah'), ('Kohat', 'Kohat'), ('Lahore', 'Lahore'), ('Larkana', 'Larkana'), ('Mandi Bahauddin', 'Mandi Bahauddin'), ('Mardan', 'Mardan'), ('Mirpur', 'Mirpur'), ('Mirpur Khas', 'Mirpur Khas'), ('Multan', 'Multan'), ('Mianwali', 'Mianwali'), ('Muzaffarabad', 'Muzaffarabad'), ('Nawabshah', 'Nawabshah'), ('Nushki', 'Nushki'), ('Okara', 'Okara'), ('Peshawar', 'Peshawar'), ('Pishin', 'Pishin'), ('Quetta', 'Quetta'), ('Rahim Yar Khan', 'Rahim Yar Khan'), ('Rawalpindi', 'Rawalpindi'), ('Sahiwal', 'Sahiwal'), ('Sargodha', 'Sargodha'), ('Shikarpur', 'Shikarpur'), ('Sheikhupura', 'Sheikhupura'), ('Sialkot', 'Sialkot'), ('Skardu', 'Skardu'), ('Swat', 'Swat'), ('Toba Tek Singh', 'Toba Tek Singh'), ('Turbat', 'Turbat'), ('Zhob', 'Zhob')], max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderPlaced',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('ordered_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Accepted', 'Accepted'), ('Packed', 'Packed'), ('On The Way', 'On The Way'), ('Delivered', 'Delivered'), ('Cancel', 'Cancel')], default='Pending', max_length=50)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.customer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product')),
            ],
        ),
    ]
